In [1]:
import numpy as np

In [2]:
# int32, float32

volume = 50
price = 100.54

In [3]:
print(type(volume))
print(type(price))

<class 'int'>
<class 'float'>


In [4]:
volume = np.int32(volume)
price = np.float32(price)

In [5]:
print(type(volume))
print(type(price))

<class 'numpy.int32'>
<class 'numpy.float32'>


In [6]:
print(np.dtype(volume))
print(np.dtype(price))

int32
float32


In [7]:
print(volume.dtype)
print(price.dtype)

int32
float32


In [8]:
array = np.array([1, 2, 3], dtype=np.float32)
array

array([1., 2., 3.], dtype=float32)

In [9]:
prices = [54.32, 56, 58.93, 57.34]

prices = np.array(prices, dtype=np.float32)

print(prices)
prices.dtype

[54.32 56.   58.93 57.34]


dtype('float32')

In [10]:
print(np.ones(5))
print(np.zeros(10))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [14]:
print(np.linspace(1, 9, 5))

[1. 3. 5. 7. 9.]


In [15]:
print(np.linspace(1, 10, 7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [16]:
prices

array([54.32, 56.  , 58.93, 57.34], dtype=float32)

In [17]:
prices[0:3]

array([54.32, 56.  , 58.93], dtype=float32)

In [18]:
prices.item(1)

56.0

In [19]:
print(prices.min())
print(prices.max())
print(prices.mean())

54.32
58.93
56.6475


In [20]:
print(prices.argmax())
print(prices.argmin())

2
0


In [21]:
print(prices.shape)
print(prices.size)

(4,)
4


In [22]:
print(prices.dtype)

float32


In [23]:
prices[1] = 57.01
prices

array([54.32, 57.01, 58.93, 57.34], dtype=float32)

In [24]:
prices.tolist()

[54.31999969482422, 57.0099983215332, 58.93000030517578, 57.34000015258789]

In [25]:
print(type(prices.tolist()))
print(type(prices))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
prices.sort()
prices

array([54.32, 57.01, 57.34, 58.93], dtype=float32)

In [27]:
doubled_prices = prices * 2
doubled_prices

array([108.64, 114.02, 114.68, 117.86], dtype=float32)

In [28]:
added_prices = prices + 10
added_prices

array([64.32    , 67.009995, 67.34    , 68.93    ], dtype=float32)

In [29]:
new_prices = np.array([100, 100, 100, 100])

final_prices = new_prices + prices
final_prices

array([154.31999969, 157.00999832, 157.34000015, 158.93000031])

In [30]:
matrix = [[1, 2], [3, 4]]
matrix

[[1, 2], [3, 4]]

In [31]:
numpy_matrix = np.array(matrix, dtype=np.float32)
numpy_matrix

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [32]:
one_to_ten = np.arange(1, 11)
one_to_ten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
matrix = one_to_ten.reshape(2, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
four_by_five = np.arange(1, 21).reshape(4, 5)
four_by_five

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
grid = np.indices((2, 3))
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [36]:
grid = np.indices((4,4))
grid

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [37]:
numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
numbers[1:, 0]

array([4, 7])

In [39]:
print(prices.size)
print(prices.shape)
print(prices.dtype)

4
(4,)
float32


In [40]:
print(numbers.min())
print(numbers.max())
print(numbers.mean())

1
9
5.0


In [41]:
print(numbers.min(axis=0))
print(numbers.min(axis=1))

[1 2 3]
[1 4 7]


In [42]:
numbers[1].min()

4

In [43]:
numbers = np.array([[3, 2, 5], [1, 4, 2], [8, 9, 11]])

print(numbers.argmax(axis=0))
print(numbers.argmax(axis=1))

[2 2 2]
[2 1 2]


In [44]:
numbers

array([[ 3,  2,  5],
       [ 1,  4,  2],
       [ 8,  9, 11]])

In [45]:
numbers[0] = np.array([2, 4, 3])
numbers

array([[ 2,  4,  3],
       [ 1,  4,  2],
       [ 8,  9, 11]])

In [46]:
numbers[0, 1] = 5
numbers

array([[ 2,  5,  3],
       [ 1,  4,  2],
       [ 8,  9, 11]])

In [47]:
numbers[:, 0] = np.array([1, 5, 5])
numbers

array([[ 1,  5,  3],
       [ 5,  4,  2],
       [ 5,  9, 11]])

In [48]:
# reshape, flatten, dot, transpose

prices = np.array([[1, 2, 3], [4, 5, 6]])
prices

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
reshaped_prices = prices.reshape(3, 2)
reshaped_prices

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
prices.flatten()

array([1, 2, 3, 4, 5, 6])

In [51]:
dot_product_1 = reshaped_prices.dot(prices)
dot_product_1

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [52]:
dot_product_2 = prices.dot(reshaped_prices)
dot_product_2

array([[22, 28],
       [49, 64]])

In [53]:
my_numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
transposed = my_numbers.transpose()
transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])