In [1]:
import numpy as np

In [2]:
# int32, float32

volume = 50
price = 100.54

In [3]:
print(type(volume))
print(type(price))

<class 'int'>
<class 'float'>


In [4]:
volume = np.int32(volume)
price = np.float32(price)

In [5]:
print(type(volume))
print(type(price))

<class 'numpy.int32'>
<class 'numpy.float32'>


In [6]:
print(np.dtype(volume))
print(np.dtype(price))

int32
float32


In [7]:
print(volume.dtype)
print(price.dtype)

int32
float32


In [8]:
array = np.array([1, 2, 3], dtype=np.float32)
array

array([1., 2., 3.], dtype=float32)

In [9]:
prices = [54.32, 56, 58.93, 57.34]

prices = np.array(prices, dtype=np.float32)

print(prices)
prices.dtype

[54.32 56.   58.93 57.34]


dtype('float32')

In [10]:
print(np.ones(5))
print(np.zeros(10))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [14]:
print(np.linspace(1, 9, 5))

[1. 3. 5. 7. 9.]
